In [1]:
import pandas as pd

In [2]:
fruits = ["Elma", "Armut", "Kiraz"]
fruits

['Elma', 'Armut', 'Kiraz']

In [3]:
pd.Series(fruits)

0     Elma
1    Armut
2    Kiraz
dtype: object

In [4]:
kırtasiye = {
    "Defter" : 30,
    "Kalem" : 20,
    "Silgi" :10
}
kırtasiye

{'Defter': 30, 'Kalem': 20, 'Silgi': 10}

In [5]:
pd.Series(kırtasiye)

Defter    30
Kalem     20
Silgi     10
dtype: int64

In [8]:
sayilar = pd.Series([1, 2, 3, 1.5])

In [16]:
sayilar.sum() # toplam
sayilar.mean() # aritmatik ortalama
sayilar.product() # çarpım
sayilar.std() #standart sapma
sayilar.min() # minimum değer
sayilar.max() # minimum değer
sayilar.median() #medyan
sayilar.mode() # mode

0    1.0
1    1.5
2    2.0
3    3.0
dtype: float64

In [17]:
deneme = pd.Series([1, 2, 3, "Soru"])

In [19]:
try:
    deneme.sum()
except:
    print("Hata")

Hata

In [20]:
len(deneme)

4

In [21]:
deneme.size

4

In [22]:
deneme2 = pd.Series([1, 2, 3, None])
deneme2

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [25]:
deneme2.size

4

In [27]:
deneme2.count()

3

In [28]:
deneme.is_unique

True

In [29]:
deneme3 = pd.Series([1, 2, 3, 2])
deneme3.is_unique

False

In [30]:
deneme3

0    1
1    2
2    3
3    2
dtype: int64

In [31]:
deneme.index

RangeIndex(start=0, stop=4, step=1)

In [32]:
deneme.values

array([1, 2, 3, 'Soru'], dtype=object)

In [33]:
gunler = ["Pazartesi", "Salı", "Çarşamba"]
meyveler = ["Elma", "Portakal", "Muz"]

pd.Series(meyveler, gunler)

Pazartesi        Elma
Salı         Portakal
Çarşamba          Muz
dtype: object

In [34]:
pd.Series(index=gunler, data=meyveler)

Pazartesi        Elma
Salı         Portakal
Çarşamba          Muz
dtype: object

In [35]:
df = pd.read_csv("resources/pokemon.csv")
df

        Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
pd.read_csv("resources/pokemon.csv", usecols=["Pokemon"])

        Pokemon
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
..          ...
716     Yveltal
717     Zygarde
718     Diancie
719       Hoopa
720   Volcanion

[721 rows x 1 columns]

In [38]:
seri = pd.read_csv("resources/pokemon.csv", 
                   usecols=["Pokemon"]).squeeze("columns")
seri

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
716       Yveltal
717       Zygarde
718       Diancie
719         Hoopa
720     Volcanion
Name: Pokemon, Length: 721, dtype: object

In [39]:
type(seri)

pandas.core.series.Series

In [42]:
seri.head()
seri.head(n=2)
seri.head(2)

0    Bulbasaur
1      Ivysaur
Name: Pokemon, dtype: object

In [45]:
seri.tail()
seri.tail(n=2)
seri.tail(2)

719        Hoopa
720    Volcanion
Name: Pokemon, dtype: object

In [46]:
dir(seri)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_convert_dtypes',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [48]:
sorted(seri, reverse=True)

['Zygarde',
 'Zweilous',
 'Zubat',
 'Zorua',
 'Zoroark',
 'Zigzagoon',
 'Zekrom',
 'Zebstrika',
 'Zapdos',
 'Zangoose',
 'Yveltal',
 'Yanmega',
 'Yanma',
 'Yamask',
 'Xerneas',
 'Xatu',
 'Wynaut',
 'Wurmple',
 'Wormadam',
 'Wooper',
 'Woobat',
 'Wobbuffet',
 'Wingull',
 'Wigglytuff',
 'Whismur',
 'Whiscash',
 'Whirlipede',
 'Whimsicott',
 'Weezing',
 'Weepinbell',
 'Weedle',
 'Weavile',
 'Watchog',
 'Wartortle',
 'Walrein',
 'Wailord',
 'Wailmer',
 'Vulpix',
 'Vullaby',
 'Voltorb',
 'Volcarona',
 'Volcanion',
 'Volbeat',
 'Vivillon',
 'Virizion',
 'Vileplume',
 'Vigoroth',
 'Victreebel',
 'Victini',
 'Vibrava',
 'Vespiquen',
 'Venusaur',
 'Venonat',
 'Venomoth',
 'Venipede',
 'Vaporeon',
 'Vanilluxe',
 'Vanillite',
 'Vanillish',
 'Uxie',
 'Ursaring',
 'Unown',
 'Unfezant',
 'Umbreon',
 'Tyrunt',
 'Tyrogue',
 'Tyrantrum',
 'Tyranitar',
 'Typhlosion',
 'Tynamo',
 'Tympole',
 'Turtwig',
 'Trubbish',
 'Tropius',
 'Trevenant',
 'Treecko',
 'Trapinch',
 'Tranquill',
 'Toxicroak',
 'Totodile',
 'Torterra',
 'Tornadus',
 'Torkoal',
 'Torchic',
 'Togetic',
 'Togepi',
 'Togekiss',
 'Tirtouga',
 'Timburr',
 'Thundurus',
 'Throh',
 'Terrakion',
 'Tepig',
 'Tentacruel',
 'Tentacool',
 'Teddiursa',
 'Tauros',
 'Tangrowth',
 'Tangela',
 'Talonflame',
 'Taillow',
 'Sylveon',
 'Swoobat',
 'Swirlix',
 'Swinub',
 'Swellow',
 'Swanna',
 'Swampert',
 'Swalot',
 'Swadloon',
 'Swablu',
 'Surskit',
 'Sunkern',
 'Sunflora',
 'Suicune',
 'Sudowoodo',
 'Stunky',
 'Stunfisk',
 'Stoutland',
 'Steelix',
 'Staryu',
 'Starmie',
 'Starly',
 'Staravia',
 'Staraptor',
 'Stantler',
 'Squirtle',
 'Spritzee',
 'Spoink',
 'Spiritomb',
 'Spinda',
 'Spinarak',
 'Spheal',
 'Spewpa',
 'Spearow',
 'Solrock',
 'Solosis',
 'Snubbull',
 'Snover',
 'Snorunt',
 'Snorlax',
 'Snivy',
 'Sneasel',
 'Smoochum',
 'Smeargle',
 'Slurpuff',
 'Slugma',
 'Slowpoke',
 'Slowking',
 'Slowbro',
 'Sliggoo',
 'Slakoth',
 'Slaking',
 'Skuntank',
 'Skrelp',
 'Skorupi',
 'Skitty',
 'Skiploom',
 'Skiddo',
 'Skarmory',
 'Simisear',
 'Simisage',
 'Simipour',
 'Silcoon',
 'Sigilyph',
 'Shuppet',
 'Shuckle',
 'Shroomish',
 'Shinx',
 'Shiftry',
 'Shieldon',
 'Shelmet',
 'Shellos',
 'Shellder',
 'Shelgon',
 'Shedinja',
 'Shaymin',
 'Sharpedo',
 'Sewaddle',
 'Seviper',
 'Servine',
 'Serperior',
 'Sentret',
 'Seismitoad',
 'Seel',
 'Seedot',
 'Sealeo',
 'Seaking',
 'Seadra',
 'Scyther',
 'Scraggy',
 'Scrafty',
 'Scolipede',
 'Scizor',
 'Sceptile',
 'Scatterbug',
 'Sawsbuck',
 'Sawk',
 'Sandslash',
 'Sandshrew',
 'Sandile',
 'Samurott',
 'Salamence',
 'Sableye',
 'Rufflet',
 'Rotom',
 'Roserade',
 'Roselia',
 'Roggenrola',
 'Riolu',
 'Rhyperior',
 'Rhyhorn',
 'Rhydon',
 'Reuniclus',
 'Reshiram',
 'Remoraid',
 'Relicanth',
 'Registeel',
 'Regirock',
 'Regigigas',
 'Regice',
 'Rayquaza',
 'Rattata',
 'Raticate',
 'Rapidash',
 'Rampardos',
 'Ralts',
 'Raikou',
 'Raichu',
 'Qwilfish',
 'Quilladin',
 'Quilava',
 'Quagsire',
 'Pyroar',
 'Purugly',
 'Purrloin',
 'Pupitar',
 'Pumpkaboo',
 'Psyduck',
 'Probopass',
 'Prinplup',
 'Primeape',
 'Porygon2',
 'Porygon-Z',
 'Porygon',
 'Poochyena',
 'Ponyta',
 'Poliwrath',
 'Poliwhirl',
 'Poliwag',
 'Politoed',
 'Plusle',
 'Piplup',
 'Pinsir',
 'Pineco',
 'Piloswine',
 'Pikachu',
 'Pignite',
 'Pidove',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Pichu',
 'Phione',
 'Phantump',
 'Phanpy',
 'Petilil',
 'Persian',
 'Pelipper',
 'Pawniard',
 'Patrat',
 'Parasect',
 'Paras',
 'Pansear',
 'Pansage',
 'Panpour',
 'Pangoro',
 'Pancham',
 'Palpitoad',
 'Palkia',
 'Pachirisu',
 'Oshawott',
 'Onix',
 'Omastar',
 'Omanyte',
 'Oddish',
 'Octillery',
 'Nuzleaf',
 'Numel',
 'Nosepass',
 'Noivern',
 'Noibat',
 'Noctowl',
 'Ninjask',
 'Ninetales',
 'Nincada',
 'Nidorino',
 'Nidorina',
 'Nidoran♂',
 'Nidoran',
 'Nidoqueen',
 'Nidoking',
 'Natu',
 'Musharna',
 'Murkrow',
 'Munna',
 'Munchlax',
 'Muk',
 'Mudkip',
 'Mr. Mime',
 'Mothim',
 'Monferno',
 'Moltres',
 'Mismagius',
 'Misdreavus',
 'Minun',
 'Minccino',
 'Mime Jr.',
 'Miltank',
 'Milotic',
 'Mightyena',
 'Mienshao',
 'Mienfoo',
 'Mewtwo',
 'Mew',
 'Metapod',
 'Metang',
 'Metagross',
 'Mesprit',
 'Meowth',
 'Meowstic',
 'Meloetta',
 'Meganium',
 'Meditite',
 'Medicham',
 'Mawile',
 'Masquerain',
 'Marshtomp',
 'Marowak',
 'Marill',
 'Mareep',
 'Maractus',
 'Mantyke',
 'Mantine',
 'Mankey',
 'Manectric',
 'Mandibuzz',
 'Manaphy',
 'Mamoswine',
 'Malamar',
 'Makuhita',
 'Magnezone',
 'Magneton',
 'Magnemite',
 'Magmortar',
 'Magmar',
 'Magikarp',
 'Magcargo',
 'Magby',
 'Machop',
 'Machoke',
 'Machamp',
 'Luxray',
 'Luxio',
 'Luvdisc',
 'Lunatone',
 'Lumineon',
 'Lugia',
 'Ludicolo',
 'Lucario',
 'Loudred',
 'Lotad',
 'Lopunny',
 'Lombre',
 'Litwick',
 'Litleo',
 'Linoone',
 'Lillipup',
 'Lilligant',
 'Lileep',
 'Liepard',
 'Lickitung',
 'Lickilicky',
 'Ledyba',
 'Ledian',
 'Leavanny',
 'Leafeon',
 'Latios',
 'Latias',
 'Larvitar',
 'Larvesta',
 'Lapras',
 'Lanturn',
 'Landorus',
 'Lampent',
 'Lairon',
 'Kyurem',
 'Kyogre',
 'Krookodile',
 'Krokorok',
 'Kricketune',
 'Kricketot',
 'Krabby',
 'Koffing',
 'Klinklang',
 'Klink',
 'Klefki',
 'Klang',
 'Kirlia',
 'Kingler',
 'Kingdra',
 'Keldeo',
 'Kecleon',
 'Karrablast',
 'Kangaskhan',
 'Kakuna',
 'Kadabra',
 'Kabutops',
 'Kabuto',
 'Jynx',
 'Jumpluff',
 'Joltik',
 'Jolteon',
 'Jirachi',
 'Jigglypuff',
 'Jellicent',
 'Ivysaur',
 'Inkay',
 'Infernape',
 'Illumise',
 'Igglybuff',
 'Hypno',
 'Hydreigon',
 'Huntail',
 'Houndour',
 'Houndoom',
 'Horsea',
 'Hoppip',
 'Hoothoot',
 'Hoopa',
 'Honedge',
 'Honchkrow',
 'Ho-oh',
 'Hitmontop',
 'Hitmonlee',
 'Hitmonchan',
 'Hippowdon',
 'Hippopotas',
 'Herdier',
 'Heracross',
 'Helioptile',
 'Heliolisk',
 'Heatran',
 'Heatmor',
 'Haxorus',
 'Hawlucha',
 'Haunter',
 'Hariyama',
 'Happiny',
 'Gyarados',
 'Gurdurr',
 'Gulpin',
 'Grumpig',
 'Growlithe',
 'Grovyle',
 'Groudon',
 'Grotle',
 'Grimer',
 'Greninja',
 'Graveler',
 'Granbull',
 'Gourgeist',
 'Gothorita',
 'Gothitelle',
 'Gothita',
 'Gorebyss',
 'Goomy',
 'Goodra',
 'Golurk',
 'Golett',
 'Golem',
 'Golduck',
 'Goldeen',
 'Golbat',
 'Gogoat',
 'Gloom',
 'Gliscor',
 'Gligar',
 'Glameow',
 'Glalie',
 'Glaceon',
 'Giratina',
 'Girafarig',
 'Gigalith',
 'Gible',
 'Geodude',
 'Gengar',
 'Genesect',
 'Gastrodon',
 'Gastly',
 'Gardevoir',
 'Garchomp',
 'Garbodor',
 'Galvantula',
 'Gallade',
 'Gabite',
 'Furret',
 'Furfrou',
 'Froslass',
 'Frogadier',
 'Froakie',
 'Frillish',
 'Fraxure',
 'Forretress',
 'Foongus',
 'Flygon',
 'Florges',
 'Floette',
 'Floatzel',
 'Fletchling',
 'Fletchinder',
 'Flareon',
 'Flabébé',
 'Flaaffy',
 'Finneon',
 'Ferrothorn',
 'Ferroseed',
 'Feraligatr',
 'Fennekin',
 'Feebas',
 'Fearow',
 "Farfetch'd",
 'Exploud',
 'Exeggutor',
 'Exeggcute',
 'Excadrill',
 'Espurr',
 'Espeon',
 'Escavalier',
 'Entei',
 'Empoleon',
 'Emolga',
 'Emboar',
 'Elgyem',
 'Elekid',
 'Electrode',
 'Electrike',
 'Electivire',
 'Electabuzz',
 'Ekans',
 'Eevee',
 'Eelektross',
 'Eelektrik',
 'Dwebble',
 'Dustox',
 'Duskull',
 'Dusknoir',
 'Dusclops',
 'Durant',
 'Duosion',
 'Dunsparce',
 'Dugtrio',
 'Ducklett',
 'Druddigon',
 'Drowzee',
 'Drilbur',
 'Drifloon',
 'Drifblim',
 'Dratini',
 'Drapion',
 'Dragonite',
 'Dragonair',
 'Dragalge',
 'Doublade',
 'Donphan',
 'Doduo',
 'Dodrio',
 'Ditto',
 'Diglett',
 'Diggersby',
 'Diancie',
 'Dialga',
 'Dewott',
 'Dewgong',
 'Deoxys',
 'Delphox',
 'Delibird',
 'Delcatty',
 'Deino',
 'Deerling',
 'Dedenne',
 'Darumaka',
 'Darmanitan',
 'Darkrai',
 'Cyndaquil',
 'Cubone',
 'Cubchoo',
 'Cryogonal',
 'Crustle',
 'Croconaw',
 'Crobat',
 'Croagunk',
 'Cresselia',
 'Crawdaunt',
 'Cranidos',
 'Cradily',
 'Cottonee',
 'Corsola',
 'Corphish',
 'Conkeldurr',
 'Combusken',
 'Combee',
 'Cofagrigus',
 'Cobalion',
 'Cloyster',
 'Cleffa',
 'Clefairy',
 'Clefable',
 'Claydol',
 'Clawitzer',
 'Clauncher',
 'Clamperl',
 'Cinccino',
 'Chingling',
 'Chinchou',
 'Chimecho',
 'Chimchar',
 'Chikorita',
 'Chespin',
 'Chesnaught',
 'Cherubi',
 'Cherrim',
 'Chatot',
 'Charmeleon',
 'Charmander',
 'Charizard',
 'Chansey',
 'Chandelure',
 'Celebi',
 'Caterpie',
 'Castform',
 'Cascoon',
 'Carvanha',
 'Carracosta',
 'Carnivine',
 'Carbink',
 'Camerupt',
 'Cacturne',
 'Cacnea',
 'Butterfree',
 'Burmy',
 'Bunnelby',
 'Buneary',
 'Bulbasaur',
 'Buizel',
 'Budew',
 'Bronzor',
 'Bronzong',
 'Breloom',
 'Braviary',
 'Braixen',
 'Bouffalant',
 'Bonsly',
 'Boldore',
 'Blitzle',
 'Blissey',
 'Blaziken',
 'Blastoise',
 'Bisharp',
 'Binacle',
 'Bidoof',
 'Bibarel',
 'Bergmite',
 'Bellsprout',
 'Bellossom',
 'Beldum',
 'Beheeyem',
 'Beedrill',
 'Beautifly',
 'Beartic',
 'Bayleef',
 'Bastiodon',
 'Basculin',
 'Barboach',
 'Barbaracle',
 'Banette',
 'Baltoy',
 'Bagon',
 'Azurill',
 'Azumarill',
 'Azelf',
 'Axew',
 'Avalugg',
 'Aurorus',
 'Audino',
 'Articuno',
 'Aron',
 'Aromatisse',
 'Armaldo',
 'Ariados',
 'Archeops',
 'Archen',
 'Arceus',
 'Arcanine',
 'Arbok',
 'Anorith',
 'Ampharos',
 'Amoonguss',
 'Ambipom',
 'Amaura',
 'Altaria',
 'Alomomola',
 'Alakazam',
 'Aipom',
 'Aggron',
 'Aerodactyl',
 'Aegislash',
 'Accelgor',
 'Absol',
 'Abra',
 'Abomasnow']

In [49]:
list(seri)

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 "Farfetch'd",
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-oh',
 'Celebi',
 'Treecko',
 'Grovyle',
 'Sceptile',
 'Torchic',
 'Combusken',
 'Blaziken',
 'Mudkip',
 'Marshtomp',
 'Swampert',
 'Poochyena',
 'Mightyena',
 'Zigzagoon',
 'Linoone',
 'Wurmple',
 'Silcoon',
 'Beautifly',
 'Cascoon',
 'Dustox',
 'Lotad',
 'Lombre',
 'Ludicolo',
 'Seedot',
 'Nuzleaf',
 'Shiftry',
 'Taillow',
 'Swellow',
 'Wingull',
 'Pelipper',
 'Ralts',
 'Kirlia',
 'Gardevoir',
 'Surskit',
 'Masquerain',
 'Shroomish',
 'Breloom',
 'Slakoth',
 'Vigoroth',
 'Slaking',
 'Nincada',
 'Ninjask',
 'Shedinja',
 'Whismur',
 'Loudred',
 'Exploud',
 'Makuhita',
 'Hariyama',
 'Azurill',
 'Nosepass',
 'Skitty',
 'Delcatty',
 'Sableye',
 'Mawile',
 'Aron',
 'Lairon',
 'Aggron',
 'Meditite',
 'Medicham',
 'Electrike',
 'Manectric',
 'Plusle',
 'Minun',
 'Volbeat',
 'Illumise',
 'Roselia',
 'Gulpin',
 'Swalot',
 'Carvanha',
 'Sharpedo',
 'Wailmer',
 'Wailord',
 'Numel',
 'Camerupt',
 'Torkoal',
 'Spoink',
 'Grumpig',
 'Spinda',
 'Trapinch',
 'Vibrava',
 'Flygon',
 'Cacnea',
 'Cacturne',
 'Swablu',
 'Altaria',
 'Zangoose',
 'Seviper',
 'Lunatone',
 'Solrock',
 'Barboach',
 'Whiscash',
 'Corphish',
 'Crawdaunt',
 'Baltoy',
 'Claydol',
 'Lileep',
 'Cradily',
 'Anorith',
 'Armaldo',
 'Feebas',
 'Milotic',
 'Castform',
 'Kecleon',
 'Shuppet',
 'Banette',
 'Duskull',
 'Dusclops',
 'Tropius',
 'Chimecho',
 'Absol',
 'Wynaut',
 'Snorunt',
 'Glalie',
 'Spheal',
 'Sealeo',
 'Walrein',
 'Clamperl',
 'Huntail',
 'Gorebyss',
 'Relicanth',
 'Luvdisc',
 'Bagon',
 'Shelgon',
 'Salamence',
 'Beldum',
 'Metang',
 'Metagross',
 'Regirock',
 'Regice',
 'Registeel',
 'Latias',
 'Latios',
 'Kyogre',
 'Groudon',
 'Rayquaza',
 'Jirachi',
 'Deoxys',
 'Turtwig',
 'Grotle',
 'Torterra',
 'Chimchar',
 'Monferno',
 'Infernape',
 'Piplup',
 'Prinplup',
 'Empoleon',
 'Starly',
 'Staravia',
 'Staraptor',
 'Bidoof',
 'Bibarel',
 'Kricketot',
 'Kricketune',
 'Shinx',
 'Luxio',
 'Luxray',
 'Budew',
 'Roserade',
 'Cranidos',
 'Rampardos',
 'Shieldon',
 'Bastiodon',
 'Burmy',
 'Wormadam',
 'Mothim',
 'Combee',
 'Vespiquen',
 'Pachirisu',
 'Buizel',
 'Floatzel',
 'Cherubi',
 'Cherrim',
 'Shellos',
 'Gastrodon',
 'Ambipom',
 'Drifloon',
 'Drifblim',
 'Buneary',
 'Lopunny',
 'Mismagius',
 'Honchkrow',
 'Glameow',
 'Purugly',
 'Chingling',
 'Stunky',
 'Skuntank',
 'Bronzor',
 'Bronzong',
 'Bonsly',
 'Mime Jr.',
 'Happiny',
 'Chatot',
 'Spiritomb',
 'Gible',
 'Gabite',
 'Garchomp',
 'Munchlax',
 'Riolu',
 'Lucario',
 'Hippopotas',
 'Hippowdon',
 'Skorupi',
 'Drapion',
 'Croagunk',
 'Toxicroak',
 'Carnivine',
 'Finneon',
 'Lumineon',
 'Mantyke',
 'Snover',
 'Abomasnow',
 'Weavile',
 'Magnezone',
 'Lickilicky',
 'Rhyperior',
 'Tangrowth',
 'Electivire',
 'Magmortar',
 'Togekiss',
 'Yanmega',
 'Leafeon',
 'Glaceon',
 'Gliscor',
 'Mamoswine',
 'Porygon-Z',
 'Gallade',
 'Probopass',
 'Dusknoir',
 'Froslass',
 'Rotom',
 'Uxie',
 'Mesprit',
 'Azelf',
 'Dialga',
 'Palkia',
 'Heatran',
 'Regigigas',
 'Giratina',
 'Cresselia',
 'Phione',
 'Manaphy',
 'Darkrai',
 'Shaymin',
 'Arceus',
 'Victini',
 'Snivy',
 'Servine',
 'Serperior',
 'Tepig',
 'Pignite',
 'Emboar',
 'Oshawott',
 'Dewott',
 'Samurott',
 'Patrat',
 'Watchog',
 'Lillipup',
 'Herdier',
 'Stoutland',
 'Purrloin',
 'Liepard',
 'Pansage',
 'Simisage',
 'Pansear',
 'Simisear',
 'Panpour',
 'Simipour',
 'Munna',
 'Musharna',
 'Pidove',
 'Tranquill',
 'Unfezant',
 'Blitzle',
 'Zebstrika',
 'Roggenrola',
 'Boldore',
 'Gigalith',
 'Woobat',
 'Swoobat',
 'Drilbur',
 'Excadrill',
 'Audino',
 'Timburr',
 'Gurdurr',
 'Conkeldurr',
 'Tympole',
 'Palpitoad',
 'Seismitoad',
 'Throh',
 'Sawk',
 'Sewaddle',
 'Swadloon',
 'Leavanny',
 'Venipede',
 'Whirlipede',
 'Scolipede',
 'Cottonee',
 'Whimsicott',
 'Petilil',
 'Lilligant',
 'Basculin',
 'Sandile',
 'Krokorok',
 'Krookodile',
 'Darumaka',
 'Darmanitan',
 'Maractus',
 'Dwebble',
 'Crustle',
 'Scraggy',
 'Scrafty',
 'Sigilyph',
 'Yamask',
 'Cofagrigus',
 'Tirtouga',
 'Carracosta',
 'Archen',
 'Archeops',
 'Trubbish',
 'Garbodor',
 'Zorua',
 'Zoroark',
 'Minccino',
 'Cinccino',
 'Gothita',
 'Gothorita',
 'Gothitelle',
 'Solosis',
 'Duosion',
 'Reuniclus',
 'Ducklett',
 'Swanna',
 'Vanillite',
 'Vanillish',
 'Vanilluxe',
 'Deerling',
 'Sawsbuck',
 'Emolga',
 'Karrablast',
 'Escavalier',
 'Foongus',
 'Amoonguss',
 'Frillish',
 'Jellicent',
 'Alomomola',
 'Joltik',
 'Galvantula',
 'Ferroseed',
 'Ferrothorn',
 'Klink',
 'Klang',
 'Klinklang',
 'Tynamo',
 'Eelektrik',
 'Eelektross',
 'Elgyem',
 'Beheeyem',
 'Litwick',
 'Lampent',
 'Chandelure',
 'Axew',
 'Fraxure',
 'Haxorus',
 'Cubchoo',
 'Beartic',
 'Cryogonal',
 'Shelmet',
 'Accelgor',
 'Stunfisk',
 'Mienfoo',
 'Mienshao',
 'Druddigon',
 'Golett',
 'Golurk',
 'Pawniard',
 'Bisharp',
 'Bouffalant',
 'Rufflet',
 'Braviary',
 'Vullaby',
 'Mandibuzz',
 'Heatmor',
 'Durant',
 'Deino',
 'Zweilous',
 'Hydreigon',
 'Larvesta',
 'Volcarona',
 'Cobalion',
 'Terrakion',
 'Virizion',
 'Tornadus',
 'Thundurus',
 'Reshiram',
 'Zekrom',
 'Landorus',
 'Kyurem',
 'Keldeo',
 'Meloetta',
 'Genesect',
 'Chespin',
 'Quilladin',
 'Chesnaught',
 'Fennekin',
 'Braixen',
 'Delphox',
 'Froakie',
 'Frogadier',
 'Greninja',
 'Bunnelby',
 'Diggersby',
 'Fletchling',
 'Fletchinder',
 'Talonflame',
 'Scatterbug',
 'Spewpa',
 'Vivillon',
 'Litleo',
 'Pyroar',
 'Flabébé',
 'Floette',
 'Florges',
 'Skiddo',
 'Gogoat',
 'Pancham',
 'Pangoro',
 'Furfrou',
 'Espurr',
 'Meowstic',
 'Honedge',
 'Doublade',
 'Aegislash',
 'Spritzee',
 'Aromatisse',
 'Swirlix',
 'Slurpuff',
 'Inkay',
 'Malamar',
 'Binacle',
 'Barbaracle',
 'Skrelp',
 'Dragalge',
 'Clauncher',
 'Clawitzer',
 'Helioptile',
 'Heliolisk',
 'Tyrunt',
 'Tyrantrum',
 'Amaura',
 'Aurorus',
 'Sylveon',
 'Hawlucha',
 'Dedenne',
 'Carbink',
 'Goomy',
 'Sliggoo',
 'Goodra',
 'Klefki',
 'Phantump',
 'Trevenant',
 'Pumpkaboo',
 'Gourgeist',
 'Bergmite',
 'Avalugg',
 'Noibat',
 'Noivern',
 'Xerneas',
 'Yveltal',
 'Zygarde',
 'Diancie',
 'Hoopa',
 'Volcanion']

In [50]:
dict(seri)

{0: 'Bulbasaur',
 1: 'Ivysaur',
 2: 'Venusaur',
 3: 'Charmander',
 4: 'Charmeleon',
 5: 'Charizard',
 6: 'Squirtle',
 7: 'Wartortle',
 8: 'Blastoise',
 9: 'Caterpie',
 10: 'Metapod',
 11: 'Butterfree',
 12: 'Weedle',
 13: 'Kakuna',
 14: 'Beedrill',
 15: 'Pidgey',
 16: 'Pidgeotto',
 17: 'Pidgeot',
 18: 'Rattata',
 19: 'Raticate',
 20: 'Spearow',
 21: 'Fearow',
 22: 'Ekans',
 23: 'Arbok',
 24: 'Pikachu',
 25: 'Raichu',
 26: 'Sandshrew',
 27: 'Sandslash',
 28: 'Nidoran',
 29: 'Nidorina',
 30: 'Nidoqueen',
 31: 'Nidoran♂',
 32: 'Nidorino',
 33: 'Nidoking',
 34: 'Clefairy',
 35: 'Clefable',
 36: 'Vulpix',
 37: 'Ninetales',
 38: 'Jigglypuff',
 39: 'Wigglytuff',
 40: 'Zubat',
 41: 'Golbat',
 42: 'Oddish',
 43: 'Gloom',
 44: 'Vileplume',
 45: 'Paras',
 46: 'Parasect',
 47: 'Venonat',
 48: 'Venomoth',
 49: 'Diglett',
 50: 'Dugtrio',
 51: 'Meowth',
 52: 'Persian',
 53: 'Psyduck',
 54: 'Golduck',
 55: 'Mankey',
 56: 'Primeape',
 57: 'Growlithe',
 58: 'Arcanine',
 59: 'Poliwag',
 60: 'Poliwhirl',
 61: 'Poliwrath',
 62: 'Abra',
 63: 'Kadabra',
 64: 'Alakazam',
 65: 'Machop',
 66: 'Machoke',
 67: 'Machamp',
 68: 'Bellsprout',
 69: 'Weepinbell',
 70: 'Victreebel',
 71: 'Tentacool',
 72: 'Tentacruel',
 73: 'Geodude',
 74: 'Graveler',
 75: 'Golem',
 76: 'Ponyta',
 77: 'Rapidash',
 78: 'Slowpoke',
 79: 'Slowbro',
 80: 'Magnemite',
 81: 'Magneton',
 82: "Farfetch'd",
 83: 'Doduo',
 84: 'Dodrio',
 85: 'Seel',
 86: 'Dewgong',
 87: 'Grimer',
 88: 'Muk',
 89: 'Shellder',
 90: 'Cloyster',
 91: 'Gastly',
 92: 'Haunter',
 93: 'Gengar',
 94: 'Onix',
 95: 'Drowzee',
 96: 'Hypno',
 97: 'Krabby',
 98: 'Kingler',
 99: 'Voltorb',
 100: 'Electrode',
 101: 'Exeggcute',
 102: 'Exeggutor',
 103: 'Cubone',
 104: 'Marowak',
 105: 'Hitmonlee',
 106: 'Hitmonchan',
 107: 'Lickitung',
 108: 'Koffing',
 109: 'Weezing',
 110: 'Rhyhorn',
 111: 'Rhydon',
 112: 'Chansey',
 113: 'Tangela',
 114: 'Kangaskhan',
 115: 'Horsea',
 116: 'Seadra',
 117: 'Goldeen',
 118: 'Seaking',
 119: 'Staryu',
 120: 'Starmie',
 121: 'Mr. Mime',
 122: 'Scyther',
 123: 'Jynx',
 124: 'Electabuzz',
 125: 'Magmar',
 126: 'Pinsir',
 127: 'Tauros',
 128: 'Magikarp',
 129: 'Gyarados',
 130: 'Lapras',
 131: 'Ditto',
 132: 'Eevee',
 133: 'Vaporeon',
 134: 'Jolteon',
 135: 'Flareon',
 136: 'Porygon',
 137: 'Omanyte',
 138: 'Omastar',
 139: 'Kabuto',
 140: 'Kabutops',
 141: 'Aerodactyl',
 142: 'Snorlax',
 143: 'Articuno',
 144: 'Zapdos',
 145: 'Moltres',
 146: 'Dratini',
 147: 'Dragonair',
 148: 'Dragonite',
 149: 'Mewtwo',
 150: 'Mew',
 151: 'Chikorita',
 152: 'Bayleef',
 153: 'Meganium',
 154: 'Cyndaquil',
 155: 'Quilava',
 156: 'Typhlosion',
 157: 'Totodile',
 158: 'Croconaw',
 159: 'Feraligatr',
 160: 'Sentret',
 161: 'Furret',
 162: 'Hoothoot',
 163: 'Noctowl',
 164: 'Ledyba',
 165: 'Ledian',
 166: 'Spinarak',
 167: 'Ariados',
 168: 'Crobat',
 169: 'Chinchou',
 170: 'Lanturn',
 171: 'Pichu',
 172: 'Cleffa',
 173: 'Igglybuff',
 174: 'Togepi',
 175: 'Togetic',
 176: 'Natu',
 177: 'Xatu',
 178: 'Mareep',
 179: 'Flaaffy',
 180: 'Ampharos',
 181: 'Bellossom',
 182: 'Marill',
 183: 'Azumarill',
 184: 'Sudowoodo',
 185: 'Politoed',
 186: 'Hoppip',
 187: 'Skiploom',
 188: 'Jumpluff',
 189: 'Aipom',
 190: 'Sunkern',
 191: 'Sunflora',
 192: 'Yanma',
 193: 'Wooper',
 194: 'Quagsire',
 195: 'Espeon',
 196: 'Umbreon',
 197: 'Murkrow',
 198: 'Slowking',
 199: 'Misdreavus',
 200: 'Unown',
 201: 'Wobbuffet',
 202: 'Girafarig',
 203: 'Pineco',
 204: 'Forretress',
 205: 'Dunsparce',
 206: 'Gligar',
 207: 'Steelix',
 208: 'Snubbull',
 209: 'Granbull',
 210: 'Qwilfish',
 211: 'Scizor',
 212: 'Shuckle',
 213: 'Heracross',
 214: 'Sneasel',
 215: 'Teddiursa',
 216: 'Ursaring',
 217: 'Slugma',
 218: 'Magcargo',
 219: 'Swinub',
 220: 'Piloswine',
 221: 'Corsola',
 222: 'Remoraid',
 223: 'Octillery',
 224: 'Delibird',
 225: 'Mantine',
 226: 'Skarmory',
 227: 'Houndour',
 228: 'Houndoom',
 229: 'Kingdra',
 230: 'Phanpy',
 231: 'Donphan',
 232: 'Porygon2',
 233: 'Stantler',
 234: 'Smeargle',
 235: 'Tyrogue',
 236: 'Hitmontop',
 237: 'Smoochum',
 238: 'Elekid',
 239: 'Magby',
 240: 'Miltank',
 241: 'Blissey',
 242: 'Raikou',
 243: 'Entei',
 244: 'Suicune',
 245: 'Larvitar',
 246: 'Pupitar',
 247: 'Tyranitar',
 248: 'Lugia',
 249: 'Ho-oh',
 250: 'Celebi',
 251: 'Treecko',
 252: 'Grovyle',
 253: 'Sceptile',
 254: 'Torchic',
 255: 'Combusken',
 256: 'Blaziken',
 257: 'Mudkip',
 258: 'Marshtomp',
 259: 'Swampert',
 260: 'Poochyena',
 261: 'Mightyena',
 262: 'Zigzagoon',
 263: 'Linoone',
 264: 'Wurmple',
 265: 'Silcoon',
 266: 'Beautifly',
 267: 'Cascoon',
 268: 'Dustox',
 269: 'Lotad',
 270: 'Lombre',
 271: 'Ludicolo',
 272: 'Seedot',
 273: 'Nuzleaf',
 274: 'Shiftry',
 275: 'Taillow',
 276: 'Swellow',
 277: 'Wingull',
 278: 'Pelipper',
 279: 'Ralts',
 280: 'Kirlia',
 281: 'Gardevoir',
 282: 'Surskit',
 283: 'Masquerain',
 284: 'Shroomish',
 285: 'Breloom',
 286: 'Slakoth',
 287: 'Vigoroth',
 288: 'Slaking',
 289: 'Nincada',
 290: 'Ninjask',
 291: 'Shedinja',
 292: 'Whismur',
 293: 'Loudred',
 294: 'Exploud',
 295: 'Makuhita',
 296: 'Hariyama',
 297: 'Azurill',
 298: 'Nosepass',
 299: 'Skitty',
 300: 'Delcatty',
 301: 'Sableye',
 302: 'Mawile',
 303: 'Aron',
 304: 'Lairon',
 305: 'Aggron',
 306: 'Meditite',
 307: 'Medicham',
 308: 'Electrike',
 309: 'Manectric',
 310: 'Plusle',
 311: 'Minun',
 312: 'Volbeat',
 313: 'Illumise',
 314: 'Roselia',
 315: 'Gulpin',
 316: 'Swalot',
 317: 'Carvanha',
 318: 'Sharpedo',
 319: 'Wailmer',
 320: 'Wailord',
 321: 'Numel',
 322: 'Camerupt',
 323: 'Torkoal',
 324: 'Spoink',
 325: 'Grumpig',
 326: 'Spinda',
 327: 'Trapinch',
 328: 'Vibrava',
 329: 'Flygon',
 330: 'Cacnea',
 331: 'Cacturne',
 332: 'Swablu',
 333: 'Altaria',
 334: 'Zangoose',
 335: 'Seviper',
 336: 'Lunatone',
 337: 'Solrock',
 338: 'Barboach',
 339: 'Whiscash',
 340: 'Corphish',
 341: 'Crawdaunt',
 342: 'Baltoy',
 343: 'Claydol',
 344: 'Lileep',
 345: 'Cradily',
 346: 'Anorith',
 347: 'Armaldo',
 348: 'Feebas',
 349: 'Milotic',
 350: 'Castform',
 351: 'Kecleon',
 352: 'Shuppet',
 353: 'Banette',
 354: 'Duskull',
 355: 'Dusclops',
 356: 'Tropius',
 357: 'Chimecho',
 358: 'Absol',
 359: 'Wynaut',
 360: 'Snorunt',
 361: 'Glalie',
 362: 'Spheal',
 363: 'Sealeo',
 364: 'Walrein',
 365: 'Clamperl',
 366: 'Huntail',
 367: 'Gorebyss',
 368: 'Relicanth',
 369: 'Luvdisc',
 370: 'Bagon',
 371: 'Shelgon',
 372: 'Salamence',
 373: 'Beldum',
 374: 'Metang',
 375: 'Metagross',
 376: 'Regirock',
 377: 'Regice',
 378: 'Registeel',
 379: 'Latias',
 380: 'Latios',
 381: 'Kyogre',
 382: 'Groudon',
 383: 'Rayquaza',
 384: 'Jirachi',
 385: 'Deoxys',
 386: 'Turtwig',
 387: 'Grotle',
 388: 'Torterra',
 389: 'Chimchar',
 390: 'Monferno',
 391: 'Infernape',
 392: 'Piplup',
 393: 'Prinplup',
 394: 'Empoleon',
 395: 'Starly',
 396: 'Staravia',
 397: 'Staraptor',
 398: 'Bidoof',
 399: 'Bibarel',
 400: 'Kricketot',
 401: 'Kricketune',
 402: 'Shinx',
 403: 'Luxio',
 404: 'Luxray',
 405: 'Budew',
 406: 'Roserade',
 407: 'Cranidos',
 408: 'Rampardos',
 409: 'Shieldon',
 410: 'Bastiodon',
 411: 'Burmy',
 412: 'Wormadam',
 413: 'Mothim',
 414: 'Combee',
 415: 'Vespiquen',
 416: 'Pachirisu',
 417: 'Buizel',
 418: 'Floatzel',
 419: 'Cherubi',
 420: 'Cherrim',
 421: 'Shellos',
 422: 'Gastrodon',
 423: 'Ambipom',
 424: 'Drifloon',
 425: 'Drifblim',
 426: 'Buneary',
 427: 'Lopunny',
 428: 'Mismagius',
 429: 'Honchkrow',
 430: 'Glameow',
 431: 'Purugly',
 432: 'Chingling',
 433: 'Stunky',
 434: 'Skuntank',
 435: 'Bronzor',
 436: 'Bronzong',
 437: 'Bonsly',
 438: 'Mime Jr.',
 439: 'Happiny',
 440: 'Chatot',
 441: 'Spiritomb',
 442: 'Gible',
 443: 'Gabite',
 444: 'Garchomp',
 445: 'Munchlax',
 446: 'Riolu',
 447: 'Lucario',
 448: 'Hippopotas',
 449: 'Hippowdon',
 450: 'Skorupi',
 451: 'Drapion',
 452: 'Croagunk',
 453: 'Toxicroak',
 454: 'Carnivine',
 455: 'Finneon',
 456: 'Lumineon',
 457: 'Mantyke',
 458: 'Snover',
 459: 'Abomasnow',
 460: 'Weavile',
 461: 'Magnezone',
 462: 'Lickilicky',
 463: 'Rhyperior',
 464: 'Tangrowth',
 465: 'Electivire',
 466: 'Magmortar',
 467: 'Togekiss',
 468: 'Yanmega',
 469: 'Leafeon',
 470: 'Glaceon',
 471: 'Gliscor',
 472: 'Mamoswine',
 473: 'Porygon-Z',
 474: 'Gallade',
 475: 'Probopass',
 476: 'Dusknoir',
 477: 'Froslass',
 478: 'Rotom',
 479: 'Uxie',
 480: 'Mesprit',
 481: 'Azelf',
 482: 'Dialga',
 483: 'Palkia',
 484: 'Heatran',
 485: 'Regigigas',
 486: 'Giratina',
 487: 'Cresselia',
 488: 'Phione',
 489: 'Manaphy',
 490: 'Darkrai',
 491: 'Shaymin',
 492: 'Arceus',
 493: 'Victini',
 494: 'Snivy',
 495: 'Servine',
 496: 'Serperior',
 497: 'Tepig',
 498: 'Pignite',
 499: 'Emboar',
 500: 'Oshawott',
 501: 'Dewott',
 502: 'Samurott',
 503: 'Patrat',
 504: 'Watchog',
 505: 'Lillipup',
 506: 'Herdier',
 507: 'Stoutland',
 508: 'Purrloin',
 509: 'Liepard',
 510: 'Pansage',
 511: 'Simisage',
 512: 'Pansear',
 513: 'Simisear',
 514: 'Panpour',
 515: 'Simipour',
 516: 'Munna',
 517: 'Musharna',
 518: 'Pidove',
 519: 'Tranquill',
 520: 'Unfezant',
 521: 'Blitzle',
 522: 'Zebstrika',
 523: 'Roggenrola',
 524: 'Boldore',
 525: 'Gigalith',
 526: 'Woobat',
 527: 'Swoobat',
 528: 'Drilbur',
 529: 'Excadrill',
 530: 'Audino',
 531: 'Timburr',
 532: 'Gurdurr',
 533: 'Conkeldurr',
 534: 'Tympole',
 535: 'Palpitoad',
 536: 'Seismitoad',
 537: 'Throh',
 538: 'Sawk',
 539: 'Sewaddle',
 540: 'Swadloon',
 541: 'Leavanny',
 542: 'Venipede',
 543: 'Whirlipede',
 544: 'Scolipede',
 545: 'Cottonee',
 546: 'Whimsicott',
 547: 'Petilil',
 548: 'Lilligant',
 549: 'Basculin',
 550: 'Sandile',
 551: 'Krokorok',
 552: 'Krookodile',
 553: 'Darumaka',
 554: 'Darmanitan',
 555: 'Maractus',
 556: 'Dwebble',
 557: 'Crustle',
 558: 'Scraggy',
 559: 'Scrafty',
 560: 'Sigilyph',
 561: 'Yamask',
 562: 'Cofagrigus',
 563: 'Tirtouga',
 564: 'Carracosta',
 565: 'Archen',
 566: 'Archeops',
 567: 'Trubbish',
 568: 'Garbodor',
 569: 'Zorua',
 570: 'Zoroark',
 571: 'Minccino',
 572: 'Cinccino',
 573: 'Gothita',
 574: 'Gothorita',
 575: 'Gothitelle',
 576: 'Solosis',
 577: 'Duosion',
 578: 'Reuniclus',
 579: 'Ducklett',
 580: 'Swanna',
 581: 'Vanillite',
 582: 'Vanillish',
 583: 'Vanilluxe',
 584: 'Deerling',
 585: 'Sawsbuck',
 586: 'Emolga',
 587: 'Karrablast',
 588: 'Escavalier',
 589: 'Foongus',
 590: 'Amoonguss',
 591: 'Frillish',
 592: 'Jellicent',
 593: 'Alomomola',
 594: 'Joltik',
 595: 'Galvantula',
 596: 'Ferroseed',
 597: 'Ferrothorn',
 598: 'Klink',
 599: 'Klang',
 600: 'Klinklang',
 601: 'Tynamo',
 602: 'Eelektrik',
 603: 'Eelektross',
 604: 'Elgyem',
 605: 'Beheeyem',
 606: 'Litwick',
 607: 'Lampent',
 608: 'Chandelure',
 609: 'Axew',
 610: 'Fraxure',
 611: 'Haxorus',
 612: 'Cubchoo',
 613: 'Beartic',
 614: 'Cryogonal',
 615: 'Shelmet',
 616: 'Accelgor',
 617: 'Stunfisk',
 618: 'Mienfoo',
 619: 'Mienshao',
 620: 'Druddigon',
 621: 'Golett',
 622: 'Golurk',
 623: 'Pawniard',
 624: 'Bisharp',
 625: 'Bouffalant',
 626: 'Rufflet',
 627: 'Braviary',
 628: 'Vullaby',
 629: 'Mandibuzz',
 630: 'Heatmor',
 631: 'Durant',
 632: 'Deino',
 633: 'Zweilous',
 634: 'Hydreigon',
 635: 'Larvesta',
 636: 'Volcarona',
 637: 'Cobalion',
 638: 'Terrakion',
 639: 'Virizion',
 640: 'Tornadus',
 641: 'Thundurus',
 642: 'Reshiram',
 643: 'Zekrom',
 644: 'Landorus',
 645: 'Kyurem',
 646: 'Keldeo',
 647: 'Meloetta',
 648: 'Genesect',
 649: 'Chespin',
 650: 'Quilladin',
 651: 'Chesnaught',
 652: 'Fennekin',
 653: 'Braixen',
 654: 'Delphox',
 655: 'Froakie',
 656: 'Frogadier',
 657: 'Greninja',
 658: 'Bunnelby',
 659: 'Diggersby',
 660: 'Fletchling',
 661: 'Fletchinder',
 662: 'Talonflame',
 663: 'Scatterbug',
 664: 'Spewpa',
 665: 'Vivillon',
 666: 'Litleo',
 667: 'Pyroar',
 668: 'Flabébé',
 669: 'Floette',
 670: 'Florges',
 671: 'Skiddo',
 672: 'Gogoat',
 673: 'Pancham',
 674: 'Pangoro',
 675: 'Furfrou',
 676: 'Espurr',
 677: 'Meowstic',
 678: 'Honedge',
 679: 'Doublade',
 680: 'Aegislash',
 681: 'Spritzee',
 682: 'Aromatisse',
 683: 'Swirlix',
 684: 'Slurpuff',
 685: 'Inkay',
 686: 'Malamar',
 687: 'Binacle',
 688: 'Barbaracle',
 689: 'Skrelp',
 690: 'Dragalge',
 691: 'Clauncher',
 692: 'Clawitzer',
 693: 'Helioptile',
 694: 'Heliolisk',
 695: 'Tyrunt',
 696: 'Tyrantrum',
 697: 'Amaura',
 698: 'Aurorus',
 699: 'Sylveon',
 700: 'Hawlucha',
 701: 'Dedenne',
 702: 'Carbink',
 703: 'Goomy',
 704: 'Sliggoo',
 705: 'Goodra',
 706: 'Klefki',
 707: 'Phantump',
 708: 'Trevenant',
 709: 'Pumpkaboo',
 710: 'Gourgeist',
 711: 'Bergmite',
 712: 'Avalugg',
 713: 'Noibat',
 714: 'Noivern',
 715: 'Xerneas',
 716: 'Yveltal',
 717: 'Zygarde',
 718: 'Diancie',
 719: 'Hoopa',
 720: 'Volcanion'}

In [57]:
seri2 = seri.copy()

In [59]:
seri2.sort_values(inplace=True)

In [60]:
seri2

459    Abomasnow
62          Abra
358        Absol
616     Accelgor
680    Aegislash
         ...
570      Zoroark
569        Zorua
40         Zubat
633     Zweilous
717      Zygarde
Name: Pokemon, Length: 721, dtype: object

In [61]:
seri2 = pd.read_csv("resources/pokemon.csv", 
                    index_col="Pokemon").squeeze("columns")
seri2

Pokemon
Bulbasaur       Grass
Ivysaur         Grass
Venusaur        Grass
Charmander       Fire
Charmeleon       Fire
               ...
Yveltal          Dark
Zygarde        Dragon
Diancie          Rock
Hoopa         Psychic
Volcanion        Fire
Name: Type, Length: 721, dtype: object

In [62]:
seri2.sort_index(inplace=True)
seri2

Pokemon
Abomasnow      Grass
Abra         Psychic
Absol           Dark
Accelgor         Bug
Aegislash      Steel
              ...
Zoroark         Dark
Zorua           Dark
Zubat         Poison
Zweilous        Dark
Zygarde       Dragon
Name: Type, Length: 721, dtype: object

In [63]:
"Abra" in seri2

True

In [64]:
"Rock" in seri2.values

True

In [65]:
seri2.index

Index(['Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aegislash', 'Aerodactyl',
       'Aggron', 'Aipom', 'Alakazam', 'Alomomola',
       ...
       'Zangoose', 'Zapdos', 'Zebstrika', 'Zekrom', 'Zigzagoon', 'Zoroark',
       'Zorua', 'Zubat', 'Zweilous', 'Zygarde'],
      dtype='object', name='Pokemon', length=721)

In [66]:
type(seri2.index)

pandas.core.indexes.base.Index

In [67]:
seri2

Pokemon
Abomasnow      Grass
Abra         Psychic
Absol           Dark
Accelgor         Bug
Aegislash      Steel
              ...
Zoroark         Dark
Zorua           Dark
Zubat         Poison
Zweilous        Dark
Zygarde       Dragon
Name: Type, Length: 721, dtype: object

In [68]:
seri2["Abra"]

'Psychic'

In [69]:
seri2[1]

'Psychic'

In [70]:
seri2[[1, 3, 5]]

Pokemon
Abra          Psychic
Accelgor          Bug
Aerodactyl       Rock
Name: Type, dtype: object

In [71]:
seri2[["Abra", "Accelgor"]]

Pokemon
Abra        Psychic
Accelgor        Bug
Name: Type, dtype: object

In [72]:
seri2[0:8]

Pokemon
Abomasnow       Grass
Abra          Psychic
Absol            Dark
Accelgor          Bug
Aegislash       Steel
Aerodactyl       Rock
Aggron          Steel
Aipom          Normal
Name: Type, dtype: object

In [73]:
seri2[0:8:2]

Pokemon
Abomasnow    Grass
Absol         Dark
Aegislash    Steel
Aggron       Steel
Name: Type, dtype: object

In [74]:
seri2[:3]

Pokemon
Abomasnow      Grass
Abra         Psychic
Absol           Dark
Name: Type, dtype: object

In [75]:
seri2[718:]

Pokemon
Zubat       Poison
Zweilous      Dark
Zygarde     Dragon
Name: Type, dtype: object

In [76]:
seri2[-1]

'Dragon'

In [77]:
seri2[-24:]

Pokemon
Wigglytuff      Normal
Wingull          Water
Wobbuffet      Psychic
Woobat         Psychic
Wooper           Water
Wormadam           Bug
Wurmple            Bug
Wynaut         Psychic
Xatu           Psychic
Xerneas          Fairy
Yamask           Ghost
Yanma              Bug
Yanmega            Bug
Yveltal           Dark
Zangoose        Normal
Zapdos        Electric
Zebstrika     Electric
Zekrom          Dragon
Zigzagoon       Normal
Zoroark           Dark
Zorua             Dark
Zubat           Poison
Zweilous          Dark
Zygarde         Dragon
Name: Type, dtype: object

In [80]:
seri2["Abra1"]

KeyError: 'Abra1'

In [84]:
seri2.get("Abra1", "Key Yok")

'Key Yok'

In [85]:
seri2["Abra"] = "Merhaba"
seri2

Pokemon
Abomasnow      Grass
Abra         Merhaba
Absol           Dark
Accelgor         Bug
Aegislash      Steel
              ...
Zoroark         Dark
Zorua           Dark
Zubat         Poison
Zweilous        Dark
Zygarde       Dragon
Name: Type, Length: 721, dtype: object

In [86]:
seri2[[0, 2, 4]] = ["A", "L", "İ"]
seri2

Pokemon
Abomasnow          A
Abra         Merhaba
Absol              L
Accelgor         Bug
Aegislash          İ
              ...
Zoroark         Dark
Zorua           Dark
Zubat         Poison
Zweilous        Dark
Zygarde       Dragon
Name: Type, Length: 721, dtype: object

In [90]:
nba = pd.read_csv("resources/nba.csv")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
type(nba)

pandas.core.frame.DataFrame

In [92]:
nba.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0

In [93]:
nba.tail(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [95]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [96]:
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [97]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [98]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [99]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [100]:
revenue = pd.read_csv("resources/revenue.csv", index_col="Date")
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [103]:
revenue.sum()
revenue.sum(axis=0)
revenue.sum(axis="index")

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [105]:
revenue.sum(axis=1)
revenue.sum(axis="columns")

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [107]:
nba.Name
nba["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [108]:
nba[["Name", "Number", "Salary"]]

              Name  Number     Salary
0    Avery Bradley     0.0  7730337.0
1      Jae Crowder    99.0  6796117.0
2     John Holland    30.0        NaN
3      R.J. Hunter    28.0  1148640.0
4    Jonas Jerebko     8.0  5000000.0
..             ...     ...        ...
453   Shelvin Mack     8.0  2433333.0
454      Raul Neto    25.0   900000.0
455   Tibor Pleiss    21.0  2900000.0
456    Jeff Withey    24.0   947276.0
457            NaN     NaN        NaN

[458 rows x 3 columns]

In [109]:
nba["College"] = "SDÜ"
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,SDÜ,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,SDÜ,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,SDÜ,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,SDÜ,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,SDÜ,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,SDÜ,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,SDÜ,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,SDÜ,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,SDÜ,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SDÜ,NaN

In [ ]:
nba.to